-- RESET DATABASE (DROP ALL TABLES)
-- CAUTION: This will delete all existing data!
DROP TABLE IF EXISTS records CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 1. Profiles Table (Linked to Supabase Auth)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('doctor', 'patient')),
  cpf TEXT UNIQUE NOT NULL,
  phone TEXT NOT NULL,
  dob DATE,
  specialty TEXT,
  price NUMERIC,
  pix TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own profile
CREATE POLICY "Users can view own profile" 
  ON public.profiles FOR SELECT 
  USING (auth.uid() = id);

-- Allow users to insert their own profile during signup
CREATE POLICY "Users can insert own profile" 
  ON public.profiles FOR INSERT 
  WITH CHECK (auth.uid() = id);

-- Allow users to update their own profile
CREATE POLICY "Users can update own profile" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

-- Allow public read access to doctor profiles (so patients can see them)
CREATE POLICY "Anyone can view doctor profiles" 
  ON public.profiles FOR SELECT 
  USING (role = 'doctor');


-- 2. Appointments Table
CREATE TABLE public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id UUID NOT NULL REFERENCES public.profiles(id),
  patient_id UUID NOT NULL REFERENCES public.profiles(id),
  date DATE NOT NULL,
  time TIME NOT NULL,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'canceled')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for appointments
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Doctors and Patients can view their own appointments
CREATE POLICY "Users can view their appointments" 
  ON public.appointments FOR SELECT 
  USING (auth.uid() = doctor_id OR auth.uid() = patient_id);

-- Patients can create appointments
CREATE POLICY "Patients can create appointments" 
  ON public.appointments FOR INSERT 
  WITH CHECK (auth.uid() = patient_id);

-- Doctors and Patients can update their own appointments (e.g., cancel)
CREATE POLICY "Users can update their appointments" 
  ON public.appointments FOR UPDATE 
  USING (auth.uid() = doctor_id OR auth.uid() = patient_id);


-- 3. Records Table (Medical Records)
CREATE TABLE public.records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id UUID NOT NULL REFERENCES public.profiles(id),
  doctor_id UUID NOT NULL REFERENCES public.profiles(id),
  date DATE NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL,
  attachment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for records
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;

-- Doctors and Patients can view relevant records
CREATE POLICY "Users can view relevant records" 
  ON public.records FOR SELECT 
  USING (auth.uid() = doctor_id OR auth.uid() = patient_id);

-- Only Doctors can create records
CREATE POLICY "Doctors can create records" 
  ON public.records FOR INSERT 
  WITH CHECK (auth.uid() = doctor_id);
