-- RESET DATABASE (DROP ALL TABLES)
-- CAUTION: This will delete all existing data!
DROP TABLE IF EXISTS records CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Enable RLS (Row Level Security)
-- NOTE: For this prototype, we are allowing ALL operations for the anonymous role.
-- In a production environment, you should restrict these policies.

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('doctor', 'patient')),
  totp_secret TEXT,
  totp_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for users" ON users FOR ALL USING (true) WITH CHECK (true);

-- 2. Patients Table
CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cpf TEXT UNIQUE NOT NULL,
  email TEXT,
  phone TEXT,
  dob DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for patients" ON patients FOR ALL USING (true) WITH CHECK (true);

-- 3. Appointments Table
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL REFERENCES users(id),
  patient_id BIGINT NOT NULL REFERENCES patients(id),
  date DATE NOT NULL,
  time TIME NOT NULL,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'canceled'))
);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for appointments" ON appointments FOR ALL USING (true) WITH CHECK (true);

-- 4. Records Table
CREATE TABLE IF NOT EXISTS records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id),
  doctor_id BIGINT NOT NULL REFERENCES users(id),
  date DATE NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL,
  attachment TEXT
);

ALTER TABLE records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for records" ON records FOR ALL USING (true) WITH CHECK (true);
